name: Project Continous Integration

on:
  push:
    branches: [ "main", "feature*", "test*" ]
  pull_request:
    branches: [ "main", "feature*" ]

jobs:
  build:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        distribution: temurin
        java-version: 8
        cache: maven
    - name: Build Code
      run: mvn -B clean package -DskipTests
    - name: Run Tests
      run: mvn -B clean verify
